version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.production
    volumes:
      - ./app:/app
    image: mishaikon/devops-for-programmers-project-74
    command: make test
