FROM node:20.12.2
WORKDIR /app

# Сначала копируем только файлы зависимостей
COPY ./app/package.json ./app/package-lock.json ./

RUN npm ci --only=production

# Затем копируем остальное
COPY ./app .

EXPOSE 8080
ENV NODE_ENV=production
RUN make build

CMD ["make", "start"]
