version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile.production
    image: mishaikon/devops-for-programmers-project-74
    environment:
      SEQUELIZE_PATH: config/config.js
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: app_db
      NODE_ENV: test
    depends_on:
      postgres:
        condition: service_healthy
    command: sh -c "npm run migrate && make test"
    volumes:
      - ./app/config:/app/config  # Монтируем папку с конфигом
      - ./app/migrations:/app/migrations  # И папку с миграциями

volumes:
  postgres_data:
