name: CI/CD Pipeline

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Hello
        run: |
          echo "START WF: check.yml"
          echo "Current dir: "
          pwd
          echo "Dir files: "
          ls

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Debug Project Structure
        run: |
          pwd
          ls -la
          echo "Contents of code directory:"
          ls -la code/ || echo "No 'code' directory found"

      - name: Verify Dockerfile
        run: |
          if [ -f Dockerfile ]; then
            echo "Dockerfile found in root directory"
            cat Dockerfile
          elif [ -f code/Dockerfile ]; then
            echo "Dockerfile found in code directory"
            cat code/Dockerfile
          else
            echo "Error: Dockerfile not found"
            exit 1
          fi

      - name: Verify docker-compose files
        run: |
          ls docker-compose*.yml
          cat docker-compose.yml

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Install Docker Compose
        run: |
          docker compose version || (
            mkdir -p ~/.docker/cli-plugins
            curl -SL https://github.com/docker/compose/releases/download/v2.24.6/docker-compose-linux-x86_64 -o ~/.docker/cli-plugins/docker-compose
            chmod +x ~/.docker/cli-plugins/docker-compose
          )

      - name: Build Docker images
        run: |
          # Ensure we're in the correct directory
          # cd ${GITHUB_WORKSPACE}
          docker compose build

      - name: Run tests
        run: |
          # Run tests using docker-compose
          docker compose up --abort-on-container-exit --exit-code-from app
