name: Node CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Hello
        run: |
          echo "START WF: hexlet-check.yml"
          echo "Current dir: "
          pwd
          echo "Dir files: "
          ls

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
      - run: |
          if [ -d app ]; then cd app; fi
          make setup
          make lint
          make test
