name: Node CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Hello
        run: |
          echo "START WF: nodejs.yml"
          echo "Current dir: "
          pwd
          echo "Dir files: "
          ls

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
          cache-dependency-path: app/package-lock.json

      - name: Install dependencies
        working-directory: ./app
        run: |
          npm ci  # Используем npm ci вместо npm install для более надежной установки
          npm audit fix --audit-level=moderate  # Автоматическое исправление уязвимостей

      - name: Run tests and linting
        working-directory: ./app
        run: |
          make lint
          make test

      - name: Run database migrations (optional)
        working-directory: ./app
        run: npm run migrate