name: Build, Test and Push to Docker Hub

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]

env:
  DOCKER_IMAGE: mishaikon/devops-for-programmers-project-74
  DOCKER_TAG: latest

jobs:
  test-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.23.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Run tests
        run: |
          docker-compose -f docker-compose.yml up --abort-on-container-exit --exit-code-from app

      - name: Build production image
        run: |
          docker-compose -f docker-compose.yml build app

      - name: Push to Docker Hub
        run: |
          docker-compose -f docker-compose.yml push app
