name: CI/CD Pipeline
on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_USER: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Hello
        run: |
          echo "START WF: push.yml"
          echo "Current dir: "
          pwd
          echo "Dir files: "
          ls

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          cd app
          npm ci   # npm install

      - name: Check package-lock.json
        run: |
          ls
          cd app
          cat package-lock.json || echo "package-lock.json not found"

      - name: Run migrations
        run: |
          cd app
          npm run migrate
        env:
          DATABASE_HOST: localhost
          DATABASE_NAME: postgres
          DATABASE_USERNAME: postgres
          DATABASE_PASSWORD: password

      - name: Run tests
        run: |
          if [ -d app ]; then cd app; fi
          npx sequelize db:migrate:undo
          npm run migrate
          make test
        env:
          DATABASE_HOST: localhost
          DATABASE_NAME: postgres
          DATABASE_USERNAME: postgres
          DATABASE_PASSWORD: password

  build-and-push:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          #context: .
          context: ./app  # Указываем путь к директории с проектом
          push: true
          tags: mishaikon/devops-for-programmers-project-74:latest
